# Generated by Django 4.2.23 on 2025-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='po_id',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='job_id',
            new_name='job',
        ),
    ]
