# Generated by Django 4.2.23 on 2025-09-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_rename_job_id_invoice_job_and_more'),
        ('purchasing', '0002_rename_contact_id_bill_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price_list_item_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem'),
        ),
    ]
