# Generated by Django 4.2.23 on 2025-09-03 22:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_estimatelineitem'),
        ('invoicing', '0003_invoicelineitem'),
        ('purchasing', '0003_remove_purchaseorder_price_list_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('central_line_item_number', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_parts_labor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('central_line_item_number', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_parts_labor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.bill')),
                ('price_list_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
            ],
            options={
                'verbose_name': 'Bill Line Item',
                'verbose_name_plural': 'Bill Line Items',
            },
        ),
    ]
