# Generated by Django 4.2.23 on 2025-09-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorderlineitem_billlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billlineitem',
            old_name='central_line_item_number',
            new_name='line_number',
        ),
        migrations.RenameField(
            model_name='billlineitem',
            old_name='unit_parts_labor',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='central_line_item_number',
            new_name='line_number',
        ),
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='unit_parts_labor',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price_list_item',
        ),
    ]
