# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_rename_central_line_item_number_billlineitem_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billlineitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
