# Generated by Django 5.2.6 on 2025-10-18 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_purchaseorder_cancel_date_purchaseorder_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('partly_paid', 'Partly Paid'), ('paid_in_full', 'Paid in Full'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
