# Generated by Django 5.2.6 on 2025-10-18 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_bill_cancelled_date_bill_created_date_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.purchaseorder'),
        ),
    ]
