# Generated by Django 5.2.5 on 2025-10-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('purchasing', '0010_alter_bill_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.business'),
        ),
    ]
