# Generated by Django 5.2.5 on 2025-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_bill_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
    ]
