# Generated by Django 5.2.5 on 2025-10-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
