# Generated by Django 5.2.5 on 2025-10-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_alter_bill_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billlineitem',
            old_name='price_currency',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='purchaseorderlineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
