# Generated by Django 5.2.6 on 2025-10-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('invoicing', '0011_pricelistitem_is_active_and_more'),
        ('jobs', '0018_alter_blep_task_and_more'),
        ('purchasing', '0014_rename_price_currency_billlineitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.pricelistitem'),
        ),
        migrations.AlterField(
            model_name='billlineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.business'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.pricelistitem'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
    ]
