# Generated by Django 5.2.5 on 2025-11-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('purchasing', '0015_alter_bill_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.business'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contacts.business'),
        ),
    ]
