# Generated by Django 5.2.5 on 2025-11-25 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('purchasing', '0016_purchaseorder_contact_alter_bill_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.business'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.business'),
        ),
    ]
