# Generated by Django 4.2.23 on 2025-09-01 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('our_reference_code', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('business_number', models.CharField(blank=True, max_length=50)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=50)),
                ('tax_cloud', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addr1', models.CharField(blank=True, max_length=255)),
                ('addr2', models.CharField(blank=True, max_length=255)),
                ('addr3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('work_number', models.CharField(blank=True, max_length=20)),
                ('home_number', models.CharField(blank=True, max_length=20)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='term_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.paymentterms'),
        ),
    ]
