# Generated by Django 5.2.5 on 2025-08-15 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Payment Terms',
                'verbose_name_plural': 'Payment Terms',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.AutoField(primary_key=True, serialize=False)),
                ('our_reference_code', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('business_number', models.CharField(blank=True, max_length=50)),
                ('tax_exemption_number', models.CharField(blank=True, max_length=50)),
                ('tax_cloud', models.CharField(blank=True, max_length=100)),
                ('term_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.paymentterms')),
            ],
        ),
    ]
