# Generated by Django 4.2.23 on 2025-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='term_id',
            new_name='terms',
        ),
    ]
