# Generated by Django 5.2.5 on 2025-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_number',
            new_name='business_phone',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
