# Generated by Django 5.2.5 on 2025-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_rename_business_number_to_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='tax_cloud',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=200),
        ),
    ]
