# Generated by Django 5.2.5 on 2025-10-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_replace_tax_cloud_with_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='our_reference_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
