# Generated by Django 5.2.5 on 2025-10-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_make_reference_code_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_business', to='contacts.contact'),
        ),
    ]
