# Generated by Django 5.2.5 on 2025-10-30 15:13

from django.db import migrations


def populate_default_contacts(apps, schema_editor):
    """Set default contact for businesses that have only one contact"""
    Business = apps.get_model('contacts', 'Business')
    Contact = apps.get_model('contacts', 'Contact')

    for business in Business.objects.all():
        contacts = Contact.objects.filter(business=business)
        if contacts.count() == 1:
            business.default_contact = contacts.first()
            business.save(update_fields=['default_contact'])


def reverse_populate_default_contacts(apps, schema_editor):
    """Clear all default contacts"""
    Business = apps.get_model('contacts', 'Business')
    Business.objects.all().update(default_contact=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_business_default_contact'),
    ]

    operations = [
        migrations.RunPython(populate_default_contacts, reverse_populate_default_contacts),
    ]
