# Generated by Django 5.2.5 on 2025-11-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_business_default_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='default_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_business', to='contacts.contact'),
        ),
    ]
