# Generated by Django 4.2.23 on 2025-09-01 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_attention', 'Needs Attention'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('customer_po_number', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_submitted_id', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=100)),
                ('assigned_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='incomplete', max_length=20)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('parent_task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMapping',
            fields=[
                ('task_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_type', models.CharField(max_length=100)),
                ('task_type_id', models.CharField(max_length=50)),
                ('breakdown_of_task', models.TextField(blank=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.workorder'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(max_length=50)),
                ('revision_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_date', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='jobs.estimate')),
            ],
            options={
                'unique_together': {('estimate_number', 'revision_number')},
            },
        ),
    ]
