# Generated by Django 4.2.23 on 2025-09-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='parent_task_id',
        ),
    ]
