# Generated by Django 5.2.5 on 2025-08-18 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estimate',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='jobs.estimate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='superseded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('estimate_number', 'revision_number')},
        ),
    ]
