# Generated by Django 4.2.23 on 2025-09-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_workorder_parent_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_id',
            new_name='assigned',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='work_order_id',
            new_name='work_order',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pre_submitted_id',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='jobs.task'),
        ),
    ]
