# Generated by Django 5.2.5 on 2025-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_estimate_created_date_estimate_superseded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer_po_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
