# Generated by Django 4.2.23 on 2025-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_assigned_id_task_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskmapping',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='job_id',
            new_name='job',
        ),
    ]
