# Generated by Django 4.2.23 on 2025-09-05 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_estimatelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blep',
            fields=[
                ('blep_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='central_line_item_number',
            new_name='line_number',
        ),
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='unit_parts_labor',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assignee',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='blep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.task'),
        ),
        migrations.AddField(
            model_name='blep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
