# Generated by Django 4.2.23 on 2025-09-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_blep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taskmapping',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('incomplete', 'Incomplete'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('task_type', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.taskmapping')),
                ('work_order_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workordertemplate')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.tasktemplate'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.workordertemplate'),
        ),
    ]
