# Generated by Django 4.2.23 on 2025-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_workordertemplate_alter_taskmapping_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='estimated_time',
        ),
        migrations.AddField(
            model_name='task',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='est_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
