# Generated by Django 4.2.23 on 2025-09-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_task_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.taskmapping'),
        ),
    ]
