# Generated by Django 5.2.6 on 2025-09-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_task_work_order_estworksheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstanceMapping',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.task')),
                ('product_identifier', models.CharField(blank=True, max_length=100)),
                ('product_instance', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmapping',
            name='task',
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='default_product_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='line_item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='line_item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taskmapping',
            name='mapping_strategy',
            field=models.CharField(choices=[('direct', 'Direct - One task to one line item'), ('bundle_to_product', 'Bundle into product line item'), ('bundle_to_service', 'Bundle into service line item'), ('exclude', 'Internal only - exclude from estimate')], default='direct', max_length=30),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='jobs.tasktemplate'),
        ),
        migrations.AddField(
            model_name='workordertemplate',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workordertemplate',
            name='product_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workordertemplate',
            name='template_type',
            field=models.CharField(choices=[('product', 'Complete Product Template'), ('service', 'Service Template'), ('process', 'Process/Workflow Template')], default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmapping',
            name='step_type',
            field=models.CharField(choices=[('product', 'Complete Product'), ('component', 'Product Component'), ('labor', 'Labor/Service'), ('material', 'Material/Supply'), ('overhead', 'Overhead/Internal')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProductBundlingRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=50)),
                ('line_item_template', models.CharField(max_length=255)),
                ('combine_instances', models.BooleanField(default=True)),
                ('pricing_method', models.CharField(choices=[('sum_components', 'Sum all component task prices'), ('template_base', 'Use WorkOrderTemplate base price'), ('custom_calculation', 'Custom calculation')], default='sum_components', max_length=20)),
                ('include_materials', models.BooleanField(default=True)),
                ('include_labor', models.BooleanField(default=True)),
                ('include_overhead', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('work_order_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.workordertemplate')),
            ],
            options={
                'ordering': ['priority', 'rule_name'],
            },
        ),
    ]
