# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_taskinstancemapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatelineitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
