# Generated by Django 5.2.6 on 2025-09-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_taskinstancemapping_remove_taskmapping_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='est_qty',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='work_order_template',
        ),
        migrations.CreateModel(
            name='TemplateTaskAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('task_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.tasktemplate')),
                ('work_order_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.workordertemplate')),
            ],
            options={
                'ordering': ['sort_order', 'task_template__template_name'],
                'unique_together': {('work_order_template', 'task_template')},
            },
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='work_order_templates',
            field=models.ManyToManyField(related_name='task_templates', through='jobs.TemplateTaskAssociation', to='jobs.workordertemplate'),
        ),
    ]
