# Generated by Django 5.2.6 on 2025-09-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_estimatelineitem_line_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='completion_date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='job',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
