# Generated by Django 5.2.6 on 2025-09-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_tasktemplate_est_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='revision_number',
            new_name='version',
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('estimate_number', 'version')},
        ),
        migrations.AddField(
            model_name='estimate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='jobs.estimate'),
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='superseded_by',
        ),
    ]
