# Generated by Django 5.2.5 on 2025-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_rename_superseded_date_estimate_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
