# Generated by Django 5.2.5 on 2025-10-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatelineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
