# Generated by Django 5.2.6 on 2025-10-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_rename_price_currency_estimatelineitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
