# Generated by Django 5.2.6 on 2025-10-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('invoicing', '0011_pricelistitem_is_active_and_more'),
        ('jobs', '0017_task_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.pricelistitem'),
        ),
        migrations.AlterField(
            model_name='estimatelineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.taskmapping'),
        ),
    ]
