# Generated by Django 5.2.5 on 2025-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='estimate_number_sequence',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='field',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='invoice_number_sequence',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='job_number_sequence',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='po_number_sequence',
        ),
        migrations.AddField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
