# Generated by Django 5.2.5 on 2025-09-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_term_id_business_terms'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(
                blank=True,
                help_text='Associated contact record for this user',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='contacts.contact'
            ),
        ),
    ]
