# Generated by Django 5.2.5 on 2025-10-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='estimate_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='invoice_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='job_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='po_counter',
            field=models.IntegerField(default=0),
        ),
    ]
