# Generated by Django 5.2.5 on 2025-10-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_configuration_estimate_number_sequence_and_more'),
        ('jobs', '0015_job_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('email_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, help_text='RFC 2822 Message-ID header', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, help_text='Associated job for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Email Record',
                'verbose_name_plural': 'Email Records',
                'db_table': 'email_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TempEmail',
            fields=[
                ('temp_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, help_text='IMAP UID for fetching message content', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.TextField(help_text='Comma-separated email addresses')),
                ('cc_email', models.TextField(blank=True, help_text='Comma-separated email addresses')),
                ('date_sent', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_data', to='core.emailrecord')),
            ],
            options={
                'verbose_name': 'Temporary Email',
                'verbose_name_plural': 'Temporary Emails',
                'db_table': 'temp_email',
                'ordering': ['-date_sent'],
                'indexes': [models.Index(fields=['-date_sent'], name='temp_email_date_se_5026a4_idx'), models.Index(fields=['uid'], name='temp_email_uid_6bd42f_idx')],
            },
        ),
    ]
