# Generated by Django 5.2.5 on 2025-10-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_configuration_estimate_number_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='key',
            field=models.CharField(db_column='config_key', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, db_column='config_value'),
        ),
    ]
