# Generated by Django 5.2.5 on 2025-08-15 02:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '__first__'),
        ('purchasing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('taxability', models.CharField(blank=True, max_length=50)),
                ('mapping_to_task', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('price_list_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('unit_parts_labor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qty_wasted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('central_line_item_number', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_parts_labor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price_currency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.bill')),
                ('estimate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.estimate')),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoice')),
                ('po_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.task')),
                ('price_list_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.pricelistitem')),
            ],
        ),
    ]
