# Generated by Django 5.2.5 on 2025-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_po_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
