# Generated by Django 4.2.23 on 2025-09-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='bill_id',
            new_name='bill',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='estimate_id',
            new_name='estimate',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='price_list_item_id',
            new_name='price_list_item',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='po_id',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='pricelistitem',
            old_name='item_type_id',
            new_name='item_type',
        ),
    ]
