# Generated by Django 4.2.23 on 2025-09-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_auto_20250903_2202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
