# Generated by Django 4.2.23 on 2025-09-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_remove_old_lineitem_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='central_line_item_number',
            new_name='line_number',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='unit_parts_labor',
            new_name='units',
        ),
        migrations.RenameField(
            model_name='pricelistitem',
            old_name='unit_parts_labor',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_po_number',
        ),
    ]
