# Generated by Django 4.2.23 on 2025-09-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_rename_central_line_item_number_invoicelineitem_line_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistitem',
            name='item_type',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
