# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_remove_pricelistitem_item_type_delete_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
