# Generated by Django 5.2.5 on 2025-10-11 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_alter_invoicelineitem_line_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded'), ('partly-paid', 'Partly Paid'), ('paid', 'Paid in Full'), ('defaulted', 'Defaulted')], default='active', max_length=20),
        ),
    ]
