# Generated by Django 5.2.5 on 2025-10-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_closed_date_invoice_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='price_currency',
            new_name='price',
        ),
    ]
