# Generated by Django 5.2.6 on 2025-10-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_rename_price_currency_invoicelineitem_price'),
        ('jobs', '0017_task_line_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='price_list_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.pricelistitem'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.task'),
        ),
    ]
